nordicopen/pymiele

pymiele/const.py, pymiele/pymiele.py, setup.cfg
Miele now recommends that a User agent string should be sent
=> Send custom User agent with requests

pymiele/pymiele.py
Events are randomly disconnecting on my production HA running on RaspberryPi3. At some point, no message is received (neither ping) and HA integration updates data only through the backup polling (60s).
This code should fix this behavior: a ping message is sent every 20s, there is a timeout of 120s on the first line of the expected response. When timeout is reached, connection is closed and re-established.
Fixed also when connection is closed externally to re-establish instead of returning.
=> Reconnect if event stream is disconnected

Makefile, pymiele/pymiele.py, pyproject.toml, requirements-dev.txt
=> Add type annotations and vendor them

Makefile, pymiele/__init__.py, pymiele/const.py, pymiele/pymiele.py, pyproject.toml, requirements-dev.txt, setup.cfg
since it's faster and easy to apply.
Ruleset is probably opinionated - those are roughly on based on home-assistant core with some simplifications.
=> Use ruff instead of isort, black and flake8

.github/workflows/ci.yml, .pre-commit-config.yaml, Makefile, requirements-dev.txt
... let's see if this works. Not sure if I can add a GH action or if this has to be done from repo owner.
=> Run ruff by pre-commit and github action

pymiele/__init__.py, pymiele/const.py, pymiele/model.py, pymiele/pymiele.py, setup.cfg
Add models for API data and prepare for moving the Miele integration to HA core
There is still room for improvement. But this version is needed for moving forward with the migration of the integration.
=> Add models for API data

.devcontainer.json, pymiele/pymiele.py, pyproject.toml, scripts/setup
Add a devcontainer to this repo
=> Add dev container

pymiele/const.py, pymiele/model.py, pymiele/pymiele.py, setup.cfg
Add more data models and correct a few glitches.
Add setter methods for datapoint that need to be updated from code. E.g. switch states.
Bump default aio timeouts to 15 s
=> Add and fix models and add setters

.github/labels.yml, .github/release-drafter.yml, .github/workflows/labels.yaml, .github/workflows/release-drafter.yaml, pyproject.toml
=> Add and update dev tools

pymiele/const.py, setup.cfg
=> Bump version -> 0.3.4

pymiele/model.py
FIx a couple of errors in data models.
Add a setter for temperatures
=> Fix data models

pymiele/model.py
=> Fix target temp and platestep models

pymiele/model.py
=> FIx spelling error bug - coreTargetTemperature

pymiele/model.py
Models for status, program_id, program_phase, and program_type
=> Add models for localized states

pymiele/__init__.py, pymiele/code_enum.py
Add class for miele program codes, etc.
Enum with automatic logging and changing to default value if code is missing.
=> Class MieleEnum

pymiele/const.py, setup.cfg
=> Bump to 0.4.0

pymiele/pymiele.py
Add PUT call to /devices/{device_id}/rooms
=> Add set_rooms endpoint

pymiele/const.py, setup.cfg
=> Bump to 0.4.1

pymiele/code_enum.py
=> Add support for duplicate values

pymiele/const.py, setup.cfg
=> Bump version -> 0.4.2

pymiele/code_enum.py, pymiele/const.py, setup.cfg
=> Adjust type

pymiele/model.py
Handle errors with incomplete or corrupt data gracefully
=> Add rubustness when value in null/None or nonExistent

pymiele/pymiele.py
Create an improved interface to API. This is designed to be set up as an instance instead of as the class itself. The latter confused mocks with Auto_spec.
=> Create better API

pymiele/code_enum.py
=> Don't log None values from API (= Unknown)

pymiele/const.py, setup.cfg
=> Prep for beta release

pymiele/code_enum.py, pymiele/const.py, setup.cfg
Modify MieleEnum to a cleaner way to trigger the missing code handling
class WashingMachinePrograms(MieleEnum, missing_to_none=True):
=> Improve MieleEnum init

pymiele/code_enum.py, pymiele/const.py, setup.cfg
=> Updated MieleEnum

pymiele/const.py, setup.cfg
=> Bump to release 0.5.5
